AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/*
    - config/application.rb
    - config/initializers/sorcery.rb
    - db/seeds/**/*
    - db/schema.rb
    - public/uploads/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
Layout/LineLength:
  Enabled: false
require:
    - rubocop-rspec
    - rubocop-rails
Style/Documentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
