AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - config/application.rb
    - config/initializers/sorcery.rb
    - db/seeds/**/*
    - db/schema.rb
    - public/uploads/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
Rails:
  Enabled: true
Layout/LineLength:
  Enabled: false
require: rubocop-rspec
Style/Documentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
